### PR TITLE
Distributed Scheduler CLI Changes

### PR DESCRIPTION
**Pull request by cicoyle**
Dapr `init`, `run`, and `uninstall` with Scheduler.

## Issue reference

https://github.com/dapr/dapr/issues/7605

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

### CODE REVIEW

**Comment by cicoyle** [comment]
Big thank you to @artursouza for the majority of the efforts for this change 🎉

**Comment by cicoyle** [comment]
Notes for the future to remember:

Planning to add to the cli these commands to a following release:
```
dapr job schedule --name=myjob --app-id=myapp --schedule "@hourly" --data '{"key":"value"}' --repeats 1
dapr job get --name=myjob --app-id=myapp
dapr job delete --name=myjob --app-id=myapp
```

**Comment by mikeee** [comment]
I'm not seeing the scheduler initialized - I've created a custom installerbundle with the scheduler added to the dapr docker image. There are no errors/warnings logged

```./
./dist/
./dist/dashboard_linux_amd64.tar.gz
./dist/injector_linux_amd64.tar.gz
./dist/scheduler_linux_amd64.tar.gz
./dist/daprd_linux_amd64.tar.gz
./dist/sentry_linux_amd64.tar.gz
./dist/placement_linux_amd64.tar.gz
./dist/operator_linux_amd64.tar.gz
./docker/
./docker/daprio-dapr-0.0.0-dev.tar.gz
./details.json
./dapr
ℹ️  Removing Dapr from your machine...
⚠  WARNING: /home/runner/.dapr/bin does not exist
⚠  WARNING: dapr_placement container does not exist
⚠  WARNING: dapr_scheduler container does not exist
⚠  WARNING: dapr_redis container does not exist
⚠  WARNING: dapr_zipkin container does not exist
⚠  WARNING: /home/runner/.dapr does not exist
✅  Dapr has been removed successfully
⌛  Making the jump to hyperspace...
⚠  Local bundle installation using --from-dir flag is currently a preview feature and is subject to change. It is only available from CLI version 1.7 onwards.
ℹ️  Installing runtime version 0.0.0-dev

Dapr runtime installed to /home/runner/.dapr/bin, you may run the following to add it to your path if you want to run daprd directly:
    export PATH=$PATH:/home/runner/.dapr/bin
Loaded image: daprio/dapr:0.0.0-dev
✅  Extracting binaries and setting up components...
✅  Extracted binaries and completed components set up.
ℹ️  daprd binary has been installed to /home/runner/.dapr/bin.
ℹ️  dapr_placement container is running.
ℹ️  Use `docker ps` to check running containers.
✅  Success! Dapr is up and running. To get started, go here: https://aka.ms/dapr-getting-started```

**Review by artursouza — APPROVED** [review]

**Comment by marcduiker** [comment]
@holopin-bot @cicoyle Thanks Cassie!

**Pull request merged**
