### PR TITLE
Fix upgrade runtime command

### PR DESCRIPTION
**Pull request by yaron2**
Fixes https://github.com/dapr/cli/issues/592

### CODE REVIEW

**Review by mukundansundar — CHANGES_REQUESTED** [review]
Change line 27

**Comment by mukundansundar** [comment]
@yaron2 should the default value be `"latest"`?

**Comment by yaron2** [comment]
> Change line 27

This is line 27, what change is needed here?

```go
	Run: func(cmd *cobra.Command, args []string) {
```

**Comment by mukundansundar** [comment]
> > Change line 27
> 
> This is line 27, what change is needed here?
> 
> ```go
> 	Run: func(cmd *cobra.Command, args []string) {
> ```

Sorry my bad ... meant 29 ...

**Review by mukundansundar — APPROVED** [review]

**Pull request merged**
