### PR TITLE
Fix flaky upgrade test

### PR DESCRIPTION
**Pull request by lrascao**
# Description

There's a flake in the upgrade test from 1.11.0 to 1.12.0, this is a version where we upgrade the `configuration` CRD by adding two new fields:`controlPlaneTrustDomain` and `sentryAddress`.
The flake stems from a known race condition that arises when both updating a CRD and a matching CR close together (described [here](https://github.com/kubernetes/kubectl/issues/1179)). This patch introduces a basic retry mechanism, it needs a fresh client on each try to the OpenAPI schema caching that's happening in the [kubectl client](https://github.com/kubernetes/kubectl/blob/master/pkg/util/openapi/openapi_getter.go#L48).

## Issue reference

No issue referenced so far but a few occurrences of the flake can be seen in the [GHA history](https://github.com/dapr/cli/actions?query=is%3Afailure)

The error is typically always the same:

```
        {"time":"2023-11-26T12:19:15.977671678Z","status":"info","msg":"Dapr control plane version 1.11.0 detected in namespace dapr-cli-tests"}
        {"time":"2023-11-26T12:19:16.073032862Z","status":"info","msg":"Starting upgrade..."}
        {"time":"2023-11-26T12:19:17.416345982Z","status":"failure","msg":"Failed to upgrade Dapr: error validating \"\": error validating data: [ValidationError(Configuration.spec.mtls): unknown field \"controlPlaneTrustDomain\" in io.dapr.v1alpha1.Configuration.spec.mtls, ValidationError(Configuration.spec.mtls): unknown field \"sentryAddress\" in io.dapr.v1alpha1.Configuration.spec.mtls]"}
```

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [X] Code compiles correctly
* [X] Created/updated tests
* [] Extended the documentation

### CODE REVIEW

**Review by mukundansundar — COMMENTED** [review]
@lrascao 
Thanks for the contribution.
Please change documentation in readme that the upgrade client now retries 5 times on failure.

**Review by yaron2 — APPROVED** [review]

**Comment by lrascao** [comment]
> @lrascao Thanks for the contribution. Please change documentation in readme that the upgrade client now retries 5 times on failure.

done, added a note to the README. lmk if something else is needed

**Review by mukundansundar — APPROVED** [review]

**Comment by lrascao** [comment]
@mukundansundar looks like the `dapr_cli` CI failure is due to the upload artifact using master (`actions/upload-artifact@master`), `v4` was released that changed the upload semantics. Pinning it down to v3 is probably the faster fix

**Comment by mukundansundar** [comment]
> @mukundansundar looks like the `dapr_cli` CI failure is due to the upload artifact using master (`actions/upload-artifact@master`), `v4` was released that changed the upload semantics. Pinning it down to v3 is probably the faster fix

Agreed ...

**Pull request merged**
