### PR TITLE
Modify path DaprRoot add the SystemDrive environment variable

### PR DESCRIPTION
**Pull request by hueifeng**
# Description

`DaprRoot` defaults to` C:/Ddapr`, but it does not rule out the possibility of SystemDrive that is not `C:`.

### CODE REVIEW

**Comment by hueifeng** [comment]
ping

**Comment by mukundansundar** [comment]
@artursouza @yaron2 Was there any particular reason to select `C:` to install Dapr ? And is it ok to change to SystemDrive from `C:` ? 

@hueifeng Based on this reply, this might also need some document changes ... Will ping you on that once we get a reply for this.

**Comment by hueifeng** [comment]
@mukundansundar Okay, thank you for your reply.

**Comment by yaron2** [comment]
> @artursouza @yaron2 Was there any particular reason to select `C:` to install Dapr ? And is it ok to change to SystemDrive from `C:` ?
> 
> @hueifeng Based on this reply, this might also need some document changes ... Will ping you on that once we get a reply for this.

I think it should be fine

**Review by mukundansundar — DISMISSED** [review]

**Review by pravinpushkar — CHANGES_REQUESTED** [review]
@hueifeng I think below line can also be changed - 
https://github.com/dapr/cli/blob/c93117963654813db59abd8c560438725450d136/.github/workflows/installdaprwin.yml#L51

**Comment by hueifeng** [comment]
@mukundansundar look ` Files changed 2` is normal?

**Comment by mukundansundar** [comment]
> @mukundansundar look ` Files changed 2` is normal?

But why are there 25 commits? And also commits that actually are not part of this PR?

**Comment by hueifeng** [comment]
@mukundansundar I suspect it was because the PR was committed a while ago, so when I changed it again, I merged the `master` content.

**Comment by hueifeng** [comment]
> @mukundansundar I suspect it was because the PR was committed a while ago, so when I changed it again, I merged the `master` content.

Need to solve this problem?

**Comment by hueifeng** [comment]
> @hueifeng There are other commits that are already there in master ... Can you fix it ? Probably rebase ?

@mukundansundar I think of it ,this happened when I signed the `DOC` after I made the change.

**Comment by mukundansundar** [comment]
> > @hueifeng There are other commits that are already there in master ... Can you fix it ? Probably rebase ?
> 
> 
> 
> @mukundansundar I think of it ,this happened when I signed the `DOC` after I made the change.

This needs to be fixed please.

**Comment by hueifeng** [comment]
@mukundansundar Please help to see whether it is right, I feel when performing `Update branch` after there will be other commit.

**Review by pravinpushkar — APPROVED** [review]
LGTM

**Review by mukundansundar — DISMISSED** [review]
Lgtm.

**Comment by pravinpushkar** [comment]
@hueifeng Thanks for making the suggested changes. For this documentation also has to be updated [here](https://docs.dapr.io/getting-started/install-dapr-cli/#install-from-command-prompt) and the [README] (https://github.com/dapr/cli#installing-dapr-cli) also needs an update.

**Review by mukundansundar — APPROVED** [review]

**Review by pravinpushkar — APPROVED** [review]

**Pull request merged**
