### PR TITLE
changed kind e2e k8s versions

### LINKED ISSUE #914: Change E2E KinD k8s versions to mirror dapr/dapr KinD-e2e
## Describe the proposal
See the following file for the versions used and change the kind e2e files in CLI repo to use the same k8s versions and SHA.
https://github.com/dapr/dapr/blob/master/.github/workflows/kind-e2e.yaml#L65-L84

## Release Note

RELEASE NOTE:

### PR DESCRIPTION
**Pull request by sourikghosh**
Signed-off-by: Sourik Ghosh <sourikghosh31@gmail.com>

# Description
changes kind e2e k8s version and SHA.
_Please explain the changes you've made_

## Issue reference
closes #914

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

### CODE REVIEW

**Comment by sourikghosh** [comment]
@mukundansundar review

**Comment by mukundansundar** [comment]
@sourikghosh Thanks for the quick PR. Can you also make the change in the upgrade_e2e workflow to use the same versions of k8s?

**Review by mukundansundar — COMMENTED** [review]
@sourikghosh Thanks for the quick PR. Can you also make the change in the upgrade_e2e workflow to use the same versions of k8s?

**Review by mukundansundar — COMMENTED** [review]
@sourikghosh Thanks for this great contribution. 
Do you think you can take a look at the latest 0.12.0 release of kind and use that in the build ?
Rest of the changes look great.

**Comment by mukundansundar** [comment]
@sourikghosh The sea versions seem to be different in the release notes for 0.12.0 ...

**Comment by sourikghosh** [comment]
Are you talking about the Images built SHA for 0.12.0 release ?? 

`1.23: kindest/node:v1.23.4@sha256:0e34f0d0fd448aa2f2819cfd74e99fe5793a6e4938b328f657c8e3f81ee0dfb9`
`1.22: kindest/node:v1.22.7@sha256:1dfd72d193bf7da64765fd2f2898f78663b9ba366c2aa74be1fd7498a1873166`
`1.21: kindest/node:v1.21.10@sha256:84709f09756ba4f863769bdcabe5edafc2ada72d3c8c44d6515fc581b66b029c`
`1.20: kindest/node:v1.20.15@sha256:393bb9096c6c4d723bb17bceb0896407d7db581532d11ea2839c80b28e5d8deb`

**Comment by mukundansundar** [comment]
> Are you talking about the Images built SHA for 0.12.0 release ??
> 
> `1.23: kindest/node:v1.23.4@sha256:0e34f0d0fd448aa2f2819cfd74e99fe5793a6e4938b328f657c8e3f81ee0dfb9` `1.22: kindest/node:v1.22.7@sha256:1dfd72d193bf7da64765fd2f2898f78663b9ba366c2aa74be1fd7498a1873166` `1.21: kindest/node:v1.21.10@sha256:84709f09756ba4f863769bdcabe5edafc2ada72d3c8c44d6515fc581b66b029c` `1.20: kindest/node:v1.20.15@sha256:393bb9096c6c4d723bb17bceb0896407d7db581532d11ea2839c80b28e5d8deb`

yes

**Review by mukundansundar — APPROVED** [review]
LGTM !!

**Pull request merged**
