### PR TITLE
Remove airgap preview feature log

### PR DESCRIPTION
**Pull request by shivamkm07**
Signed-off-by: Shivam Kumar <shivamkm07@gmail.com>

# Description

Dapr Airgap init currently gives a warning that it is a preview feature. We can remove the warning now since there is no breaking change planned  and it has been in preview for 3 releases now. 

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #928 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

### CODE REVIEW

**Review by mukundansundar — DISMISSED** [review]
lgtm

**Comment by mukundansundar** [comment]
@shivamkm07 If possible can you add e2e for https://github.com/dapr/cli/issues/928 in the installer bundle repo?

**Comment by mukundansundar** [comment]
Then we can move the feature to stable?

**Comment by shivamkm07** [comment]
> @shivamkm07 If possible can you add e2e for #928 in the installer bundle repo?

I have added the e2e test for airgap in cli in the same PR.

**Comment by shivamkm07** [comment]
Should this PR be rebased to master as the PR has been added to 1.11 milestone?

**Comment by mukundansundar** [comment]
also related to #1080

**Pull request closed without merging**
