### PR TITLE
fix some typos in installation script

### PR DESCRIPTION
**Pull request by zzxwill**
# Description

_Please explain the changes you've made_

Just to fix some typos in those installation scripts.

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Related to #527

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ x ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

### CODE REVIEW

**Comment by zzxwill** [comment]
I found these issues when I was trying to implement the install of KubeVela Cli by script. 
Also want to make sure, under Dapr Cli's license MIT, whether is it proper for the implementation to be based on Dapr cli with the copyright kept? Thanks.
PR: https://github.com/oam-dev/kubevela/pull/667

install.sh sample:
```
# ------------------------------------------------------------
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
# ------------------------------------------------------------
param (
    [string]$Version,
    [string]$VelaRoot = "c:\vela"
)

Write-Output ""
$ErrorActionPreference = 'stop'

#Escape space of VelaRoot path
$VelaRoot = $VelaRoot -replace ' ', '` '
```

**Comment by mukundansundar** [comment]
> I found these issues when I was trying to implement the install of KubeVela Cli by script.
> Also want to make sure, under Dapr Cli's license MIT, whether is it proper for the implementation to be based on Dapr cli with the copyright kept? Thanks.
> PR: [oam-dev/kubevela#667](https://github.com/oam-dev/kubevela/pull/667)
> 
> install.sh sample:
> 
> ```
> # ------------------------------------------------------------
> # Copyright (c) Microsoft Corporation.
> # Licensed under the MIT License.
> # ------------------------------------------------------------
> param (
>     [string]$Version,
>     [string]$VelaRoot = "c:\vela"
> )
> 
> Write-Output ""
> $ErrorActionPreference = 'stop'
> 
> #Escape space of VelaRoot path
> $VelaRoot = $VelaRoot -replace ' ', '` '
> ```

@yaron2 can you reply for the license comment?

**Comment by zzxwill** [comment]
I cited the source of Dapr at the begining as below in the file https://github.com/oam-dev/kubevela/blob/master/docs/install.sh.

```
#!/usr/bin/env bash

# Implemented based on Dapr Cli https://github.com/dapr/cli/tree/master/install

# Vela CLI location
: ${VELA_INSTALL_DIR:="/usr/local/bin"}
```

**Comment by yaron2** [comment]
> I cited the source of Dapr at the begining as below in the file https://github.com/oam-dev/kubevela/blob/master/docs/install.sh.
> 
> ```
> #!/usr/bin/env bash
> 
> # Implemented based on Dapr Cli https://github.com/dapr/cli/tree/master/install
> 
> # Vela CLI location
> : ${VELA_INSTALL_DIR:="/usr/local/bin"}
> ```

The citing is fine. The MIT license allows you to base your implementation on the Dapr CLI.

**Review by mukundansundar — APPROVED** [review]

**Comment by yaron2** [comment]
Thanks for your contribution

**Comment by yaron2** [comment]
Thanks for this PR @zzxwill

**Pull request merged**
