### PR TITLE
Run: pass missing env variables

### PR DESCRIPTION
**Pull request by anhldbk**
# Description

- In the past, I opened this PR: https://github.com/dapr/cli/pull/770. Changes look like a mess. I close the PR and made this one.
- CLI only passes 03 env variables to applications. See [run.go#L185-L187](https://github.com/dapr/cli/blob/master/pkg/standalone/run.go#L185-L187)
- There are more.  See [Docs](https://docs.dapr.io/reference/environment/)
- Python SDK has a different view on such variables. See [global_settings.py](https://github.com/dapr/python-sdk/blob/master/dapr/conf/global_settings.py). This leads to `not-working` [tutorial](https://docs.dapr.io/developing-applications/building-blocks/service-invocation/howto-invoke-discover-services/#step-1-choose-an-id-for-your-service)

# Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Add tests for CLI (run command) to validate env variables
* [x] Modify code to pass the missing variables
* [x] Refactor code (run.go can be cleaner)
* [x] Update documentation: https://github.com/dapr/docs/pull/1835

### CODE REVIEW

**Comment by anhldbk** [comment]
@yaron2 PTAL

**Comment by yaron2** [comment]
LGTM overall.

@mukundansundar can you please take one last look before we merge?

**Comment by anhldbk** [comment]
@mukundansundar I wish this PR is merged on Jan 1st 2022. Would you pls make my dream come true?

**Comment by mukundansundar** [comment]
LGTM overall ...

**Comment by mukundansundar** [comment]
Overall looks good ... But my question still remains as to whether we need to expose these variables as ENV vars ... that too without DAPR prefix ...

**Comment by anhldbk** [comment]
@mukundansundar Happy new year :)

For your question, I already made a PR in our docs. Pls see
- The PR: https://github.com/dapr/docs/pull/1835
- The doc: https://docs.dapr.io/reference/environment/

**Review by yaron2 — APPROVED** [review]

**Comment by anhldbk** [comment]
@yaron2 @mukundansundar  yay. You make my day. Thank you!

**Comment by rabollin** [comment]
@mukundansundar - Please prioritize this to get into 1.6 CLI release.

**Pull request merged**
