### PR TITLE
kill all instances of apps started by same run file

### PR DESCRIPTION
**Pull request by pravinpushkar**
Signed-off-by: Pravin Pushkar <ppushkar@microsoft.com>

# Description

Same run template can be used to run multiple times to start apps with same `appID`. Say if  the run template has 2 apps and `dapr run -f <>` is run twice by keeping same `appID` then we would have total 4 apps started by same run template file.

In the above case, `dapr stop -f <>` will stop any one set of apps from the 2 sets. We should be able to stop instances of apps started by the same template file.

This can also been seen with normal `dapr run` but this PR only addresses the template stop.

### CODE REVIEW

**Comment by pravinpushkar** [comment]
#### 1st set of apps - 

➜  distributed-calculator git:(master) ✗ ldapr run -f .    
ℹ️  Validating config and starting app "addapp"
ℹ️  Started Dapr with app id "addapp". HTTP Port: 3513. gRPC Port: 54245
ℹ️  Writing log files to directory : /Users/pravin/work/quickstarts/tutorials/distributed-calculator/go/.dapr/logs
ℹ️  Validating config and starting app "subtractapp"
ℹ️  Started Dapr with app id "subtractapp". HTTP Port: 3512. gRPC Port: 54280
ℹ️  Writing log files to directory : /Users/pravin/work/quickstarts/tutorials/distributed-calculator/node/.dapr/logs
ℹ️  Validating config and starting app "multiplyapp"
ℹ️  Started Dapr with app id "multiplyapp". HTTP Port: 3511. gRPC Port: 54331
ℹ️  Writing log files to directory : /Users/pravin/work/quickstarts/tutorials/distributed-calculator/python/.dapr/logs
ℹ️  Validating config and starting app "subtractapp"
ℹ️  Started Dapr with app id "subtractapp". HTTP Port: 3514. gRPC Port: 54388
ℹ️  Writing log files to directory : /Users/pravin/work/quickstarts/tutorials/distributed-calculator/csharp/.dapr/logs
ℹ️  Validating config and starting app "frontendapp"
ℹ️  Started Dapr with app id "frontendapp". HTTP Port: 3517. gRPC Port: 54438
ℹ️  Writing log files to directory : /Users/pravin/work/quickstarts/tutorials/distributed-calculator/react-calculator/.dapr/logs

#### 2nd set of apps - 
➜  distributed-calculator git:(master) ✗ ldapr run -f .
ℹ️  Validating config and starting app "addapp"
ℹ️  Started Dapr with app id "addapp". HTTP Port: 3503. gRPC Port: 54503
ℹ️  Writing log files to directory : /Users/pravin/work/quickstarts/tutorials/distributed-calculator/go/.dapr/logs
ℹ️  Validating config and starting app "subtractapp"
ℹ️  Started Dapr with app id "subtractapp". HTTP Port: 3502. gRPC Port: 54531
ℹ️  Writing log files to directory : /Users/pravin/work/quickstarts/tutorials/distributed-calculator/node/.dapr/logs
ℹ️  Validating config and starting app "multiplyapp"
ℹ️  Started Dapr with app id "multiplyapp". HTTP Port: 3501. gRPC Port: 54558
ℹ️  Writing log files to directory : /Users/pravin/work/quickstarts/tutorials/distributed-calculator/python/.dapr/logs
ℹ️  Validating config and starting app "subtractapp"
ℹ️  Started Dapr with app id "subtractapp". HTTP Port: 3504. gRPC Port: 54585
ℹ️  Writing log files to directory : /Users/pravin/work/quickstarts/tutorials/distributed-calculator/csharp/.dapr/logs
ℹ️  Validating config and starting app "frontendapp"
ℹ️  Started Dapr with app id "frontendapp". HTTP Port: 3507. gRPC Port: 54612
ℹ️  Writing log files to directory : /Users/pravin/work/quickstarts/tutorials/distributed-calculator/react-calculator/.dapr/logs


#### dapr list output - 
APP ID       HTTP PORT  GRPC PORT  APP PORT  COMMAND               AGE  CREATED              DAPRD PID  CLI PID  RUN TEMPLATE PATH
  frontendapp  3507       54612      8080      node server.js        14s  2023-02-04 16:34.09  17730      17596    /Users/pravin/work/quickstarts/tutorials/distributed-calculator/dapr.yaml
  subtractapp  3504       54585      7001      dotnet ./bin/Debu...  15s  2023-02-04 16:34.08  17706      17596    /Users/pravin/work/quickstarts/tutorials/distributed-calculator/dapr.yaml
  multiplyapp  3501       54558      5001      flask run             16s  2023-02-04 16:34.07  17675      17596    /Users/pravin/work/quickstarts/tutorials/distributed-calculator/dapr.yaml
  subtractapp  3502       54531      4000      node app.js           18s  2023-02-04 16:34.05  17651      17596    /Users/pravin/work/quickstarts/tutorials/distributed-calculator/dapr.yaml
  addapp       3503       54503      6000      go run app.go         19s  2023-02-04 16:34.04  17612      17596    /Users/pravin/work/quickstarts/tutorials/distributed-calculator/dapr.yaml

  frontendapp  3517       54438      8080      node server.js        1m   2023-02-04 16:32.54  17306      17221    /Users/pravin/work/quickstarts/tutorials/distributed-calculator/dapr.yaml
  subtractapp  3514       54388      7001      dotnet ./bin/Debu...  1m   2023-02-04 16:32.53  17290      17221    /Users/pravin/work/quickstarts/tutorials/distributed-calculator/dapr.yaml
  multiplyapp  3511       54331      5001      flask run             1m   2023-02-04 16:32.52  17268      17221    /Users/pravin/work/quickstarts/tutorials/distributed-calculator/dapr.yaml
  subtractapp  3512       54280      4000      node app.js           1m   2023-02-04 16:32.51  17258      17221    /Users/pravin/work/quickstarts/tutorials/distributed-calculator/dapr.yaml
  addapp       3513       54245      6000      go run app.go         1m   2023-02-04 16:32.50  17227      17221    /Users/pravin/work/quickstarts/tutorials/distributed-calculator/dapr.yaml

#### dapr stop -f with this fix - 
Screenshot 2023-02-04 at 4 36 10 PM

#### dapr list output - 
➜  cli git:(stop_all) ldapr list
No Dapr instances found.

**Review by mukundansundar — COMMENTED** [review]
@pravinpushkar please add an E2E for the same.

**Comment by mukundansundar** [comment]
@pravinpushkar move to master as target branch and rebase with master.

**Comment by mukundansundar** [comment]
I am thinking that instead of this to fully support apps with same app IDs, we would have to clearly support stopping of particular instances of apps. 
With same appIDs, we will not have a unique identifier to then stop a particular instance. I think that is the problem we need to fix first.

**Comment by pravinpushkar** [comment]
> I am thinking that instead of this to fully support apps with same app IDs, we would have to clearly support stopping of particular instances of apps. With same appIDs, we will not have a unique identifier to then stop a particular instance. I think that is the problem we need to fix first.

I am thinking should we associate all `dapr run` runs with a unique runID which can be `${appID}_${randomUniqueID}`. 
With this we can enhance `dapr stop` in the following way - 
1. dapr stop appID -> Will stop all instances of apps with the same app ID
2. dapr stop runID -> will stop a particular instance of `dapr run`. The `runID` will have to be fetched from `dapr list` by users. We can also output the runID in logs for easy reference.

**Comment by pravinpushkar** [comment]
> > I am thinking that instead of this to fully support apps with same app IDs, we would have to clearly support stopping of particular instances of apps. With same appIDs, we will not have a unique identifier to then stop a particular instance. I think that is the problem we need to fix first.
> 
> I am thinking should we associate all `dapr run` runs with a unique runID which can be `${appID}_${randomUniqueID}`. With this we can enhance `dapr stop` in the following way -
> 
> 1. dapr stop appID -> Will stop all instances of apps with the same app ID
> 2. dapr stop runID -> will stop a particular instance of `dapr run`. The `runID` will have to be fetched from `dapr list` by users. We can also output the runID in logs for easy reference.

@mukundansundar @yaron2 any thoughts on this ?

**Comment by mukundansundar** [comment]
> > > I am thinking that instead of this to fully support apps with same app IDs, we would have to clearly support stopping of particular instances of apps. With same appIDs, we will not have a unique identifier to then stop a particular instance. I think that is the problem we need to fix first.
> > 
> > 
> > I am thinking should we associate all `dapr run` runs with a unique runID which can be `${appID}_${randomUniqueID}`. With this we can enhance `dapr stop` in the following way -
> > 
> > 1. dapr stop appID -> Will stop all instances of apps with the same app ID
> > 2. dapr stop runID -> will stop a particular instance of `dapr run`. The `runID` will have to be fetched from `dapr list` by users. We can also output the runID in logs for easy reference.
> 
> @mukundansundar @yaron2 any thoughts on this ?

In this case the `daprd` `--appId` flag will still be only `appID` but only the metadata will will have an additional `runID` stored?

**Comment by pravinpushkar** [comment]
> > > > I am thinking that instead of this to fully support apps with same app IDs, we would have to clearly support stopping of particular instances of apps. With same appIDs, we will not have a unique identifier to then stop a particular instance. I think that is the problem we need to fix first.
> > > 
> > > 
> > > I am thinking should we associate all `dapr run` runs with a unique runID which can be `${appID}_${randomUniqueID}`. With this we can enhance `dapr stop` in the following way -
> > > 
> > > 1. dapr stop appID -> Will stop all instances of apps with the same app ID
> > > 2. dapr stop runID -> will stop a particular instance of `dapr run`. The `runID` will have to be fetched from `dapr list` by users. We can also output the runID in logs for easy reference.
> > 
> > 
> > @mukundansundar @yaron2 any thoughts on this ?
> 
> In this case the `daprd` `--appId` flag will still be only `appID` but only the metadata will will have an additional `runID` stored?

yes, right. We can have something like `dapr stop --run-id app1_randomstr`

**Comment by mukundansundar** [comment]
@pravinpushkar I suggest closing this PR, open an issue with all that we discussed and complete the discussion and then open a new Pr with the Implementation as this requires introduction of a `runID` which is not in scope for this PR. Wdyt?

**Comment by pravinpushkar** [comment]
> @pravinpushkar I suggest closing this PR, open an issue with all that we discussed and complete the discussion and then open a new Pr with the Implementation as this requires introduction of a `runID` which is not in scope for this PR. Wdyt?

That make sense, I will open a separate issue.

**Pull request closed without merging**
