### PR TITLE
optimize/upgrade: dashboard should be not participate in the calculation 

### PR DESCRIPTION
**Pull request by 1046102779**
dapr-dashboard maybe exist in dapr-monitoring, not in dapr-system.  I thinks cli tools should not check dapr-dashboard. 

Because I encountered a problem, when my dashboard was deployed separately in dapr-monitoring, but I did not delete the dashboard in dapr-system, if I deploy the Dapr cluster in a non-highly available way, when I use **dapr upgrade -k --runtime-version=xxx**, because the number of dashboards exceeds 1, a highly available cluster is created. At this time, placement-server is a statefulset, and it has no other 2 PODs to scroll, resulting in the following error:

image

Although the cli tool reported an error, the cluster was created successfully, and the number of placement-servers was not highly available:

image

### CODE REVIEW

**Comment by 1046102779** [comment]
@yaron2 @artursouza @pkedy +1

**Review by mukundansundar — COMMENTED** [review]
lgtm.

/cc @yaron2 ?

**Comment by mukundansundar** [comment]
@yaron2 can you review this PR?

**Comment by mukundansundar** [comment]
@yaron2 Can you review this PR ?

**Review by mukundansundar — APPROVED** [review]
@yaron2 Please review this change

**Review by yaron2 — APPROVED** [review]

**Pull request merged**
