### PR TITLE
Add --all flag to kubernetes uninstall

### LINKED ISSUE #656: Dapr uninstall -k does not remove the CRDs
## Expected Behavior

`dapr uninstall -k` remove the CRDs

## Actual Behavior
```
$ dapr uninstall -k
ℹ️  Removing Dapr from your cluster...
✅  Dapr has been removed successfully
$ kubectl get crds
NAME                     CREATED AT
components.dapr.io       2021-03-31T01:24:00Z
configurations.dapr.io   2021-03-31T01:24:00Z
subscriptions.dapr.io    2021-03-31T01:24:01Z
```

## Steps to Reproduce the Problem

- install dapr using `dapr init -k`. 
- run `kubectl get crds` 
- run `dapr uninstall -k` 
- run `kubectl get crds` 
the crds still exist. 

## Release Note

RELEASE NOTE: **RESOLVED** `dapr uninstall -k` does not remove CRDs

### PR DESCRIPTION
**Pull request by yaron2**
This PR adds the `--all` flag to a Kubernetes uninstall command to remove all CRDs.

closes #656

### CODE REVIEW

**Comment by mukundansundar** [comment]
@yaron2 Can you change the e2e tests to use the `--all` flag and remove the delete CRDs(after each test). That will be a validation for the change as well.

**Comment by yaron2** [comment]
> @yaron2 Can you change the e2e tests to use the `--all` flag and remove the delete CRDs(after each test). That will be a validation for the change as well.

Should probably add a specific uninstall test with `--all`, as we still want to make sure that regular uninstall keeps CRDs and components in place.

**Review by wcs1only — COMMENTED** [review]
Change looks good, but +1 to adding E2E tests for this feature.

**Pull request merged**
