### PR TITLE
Updating winget manifests

### PR DESCRIPTION
**Pull request by shivamkm07**
Signed-off-by: shivam <shivamkm07@gmail.com>

# Description

Updating winget manifests in every release

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #1108 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

### CODE REVIEW

**Comment by shivamkm07** [comment]
Note: This PR can only be merged after:

1. https://github.com/dapr/cli/pull/1065 is merged
2. First manifest is published to [winget-pkgs](https://github.com/microsoft/winget-pkgs), which can only be done after 1.9.0-rc.1 release as we don't have msi packages for previous releases.

**Review by mukundansundar — CHANGES_REQUESTED** [review]
> Note: This PR can only be merged after:
> 
> 
> 
> 1. https://github.com/dapr/cli/pull/1065 is merged
> 
> 2. First manifest is published to [winget-pkgs](https://github.com/microsoft/winget-pkgs), which can only be done after 1.9.0-rc.1 release as we don't have msi packages for previous releases.

Is this the recommended way to update winget repo? 
Please link documentation as comment.

Also please document as what this step does and what we should expect on completion of this step....

**Comment by shivamkm07** [comment]
> Is this the recommended way to update winget repo? Please link documentation as comment.

For every release of the package, we need to add the manifest in [winget-pkgs](https://github.com/microsoft/winget-pkgs) repo by creating a PR: https://docs.microsoft.com/en-us/windows/package-manager/package/repository

However, to simplify this process, `winget-create update` helps creating the PR automatically with updated `version` and `InstallerUrl`: https://github.com/microsoft/winget-create/blob/main/doc/update.md

But before this, a new manifest needs to be added first in winget-pkgs using `winget-create new` which can be later updated using the update command: https://github.com/microsoft/winget-create/blob/main/doc/new.md. Following the same, a PR has been submitted with edge build in my fork to unblock the release pipeline: https://github.com/microsoft/winget-pkgs/pull/79840. 

> Also please document as what this step does and what we should expect on completion of this step....

This step creates a PR to [winget-pkgs](https://github.com/microsoft/winget-pkgs) with the updated manifest for the latest release. The structure of the manifest would be same as https://github.com/microsoft/winget-pkgs/pull/79840, but with updated `Version`  and `InstallerUrl`. 
Note: For this, a fork of  [winget-pkgs](https://github.com/microsoft/winget-pkgs) should exist under Dapr Org to create PR from, otherwise it would create the fork first and then create the PR using the `token` provided.

**Review by pravinpushkar — APPROVED** [review]
lgtm

**Comment by shivamkm07** [comment]
GovulnCheck is failing, but is unrelated to the PR and fixed in release-1.9: https://github.com/dapr/cli/pull/1083

**Comment by shivamkm07** [comment]
Dapr CLI 1.9.1 has been published to winget: https://github.com/microsoft/winget-pkgs/pull/83516

With this, the current PR is unblocked and can be merged. The pipeline change have been tested for both rc releases and stable releases:

RC release: https://github.com/shivamkm07/cli/actions/runs/3274827280
Stable release: https://github.com/shivamkm07/cli/actions/runs/3274981614

**Review by mukundansundar — APPROVED** [review]

**Pull request merged**
