### PR TITLE
Move trace Zipkin address into Configuration's trace section

### PR DESCRIPTION
**Pull request by tcnghia**
# Description

Move trace Zipkin address into Configuration's trace section.

I have a follow-up PR for unit testing, but it requires some additional refactoring that can be done separately.

## Issue reference

Please reference the issue this PR will close: #534 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

### CODE REVIEW

**Comment by tcnghia** [comment]
@mukundansundar can you please help reviewing the PR? thanks

**Review by mukundansundar — COMMENTED** [review]
Please change line about `zipkin.yaml` in README.md

**Comment by tcnghia** [comment]
> Please change line about `zipkin.yaml` in README.md

Good catch! Thanks a lot. Done now.

**Comment by mukundansundar** [comment]
@tcnghia Please test these changes against the latest runtime

1. make build daprd binary 
2. make build cli 
3. run `dapr init --runtime-version 1.0.0-rc.1` 
4. once initialized, replace `~/.dapr/bin/daprd` with the newly built binary. 
5. Test against any of the quickstarts and verify that traces are there.

**Comment by tcnghia** [comment]
> @tcnghia Please test these changes against the latest runtime
> 
> 1. make build daprd binary
> 2. make build cli
> 3. run `dapr init --runtime-version 1.0.0-rc.1`
> 4. once initialized, replace `~/.dapr/bin/daprd` with the newly built binary.
> 5. Test against any of the quickstarts and verify that traces are there.
> 
> make sure the configuration CRD is in the right format.

Done & confirmed

**Review by mukundansundar — APPROVED** [review]
LGTM

**Comment by mukundansundar** [comment]
@yaron2 Any thoughts on this or can it be merged?

**Review by yaron2 — APPROVED** [review]
LGTM

**Pull request merged**
