### PR TITLE
Add --wait amd --timeout flags for dapr init -k which are passed to Helm

### LINKED ISSUE #597: Add --wait flag to dapr init and dapr upgrade
## Describe the proposal

When using infrastructure as code in a DevOps pipeline my K8s cluster is created and I then run dapr init and helm install (of my application) if you do that too quickly no side cars will be injected into my pods because the dapr containers are still being created.

This required me to write custom logic to repeatedly calling dapr status and checking if I found the word `false` or not. This works but makes my pipeline fragile. If the output of dapr status were to change my pipeline would fail.

If dapr init and dapr upgrade offered a --wait flag that would cause the call to block until all the containers are healthy would eliminate the need for customer implementations of waiting logic.

## Release Note

RELEASE NOTE:

### PR DESCRIPTION
**Pull request by pkedy**
# Description

This PR adds:

* The `--wait` and `--timeout` flags to `dapr init`
* The `--timeout` flag to `dapr upgrade` and `dapr uninstall` (These two commands already wait so the desired behavior described in the issue #597 is already implemented).

This will be tested in an upcoming PR that will add e2e tests per #412.

## Issue reference

Resolves #597

## Checklist

* [x] Code compiles correctly
* [ ] Created/updated tests
* [x] Extended the documentation

### CODE REVIEW

**Comment by mukundansundar** [comment]
@pkedy should the timeout be configurable?

**Comment by pkedy** [comment]
@mukundansundar You read my mind.  The default is 300s/5m which is probably fine but having the option can't hurt.

**Comment by mukundansundar** [comment]
@pkedy Mention that in the doc and in the argument docstring?

**Comment by pkedy** [comment]
@mukundansundar Yes on the docs. No need to put the default value in the docstring since Cobra prints it out for you on a `--help`.

**Comment by mukundansundar** [comment]
@pkedy Can you look at the build? It seems to be failing ...

**Review by artursouza — DISMISSED** [review]

**Review by artursouza — APPROVED** [review]

**Pull request merged**
