### PR TITLE
ci: standard linter config

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Long <long0dai@foxmail.com>

# Description

Ref https://github.com/dapr/dapr/issues/3537

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

### CODE REVIEW

**Review by artursouza — DISMISSED** [review]

**Comment by artursouza** [comment]
@mukundansundar @yaron2 Please, review and merge.

**Review by mukundansundar — APPROVED** [review]

**Comment by daixiang0** [comment]
@yaron2 please review as maintainer.

**Comment by daixiang0** [comment]
@yaron2 please review as maintainer.

**Review by mukundansundar — APPROVED** [review]

**Comment by daixiang0** [comment]
ping @yaron2

**Comment by mukundansundar** [comment]
Thanks for the PR!

**Pull request merged**
