### PR TITLE
Make internal-grpc-port option configurable

### PR DESCRIPTION
**Pull request by shubham1172**
# Description

Continued from #876

Adds a new Dapr run flag to accept a port number for Dapr's internal gRPC API. See [source](https://github.com/dapr/dapr/blob/08a100eda31bffcff929811f14ec79fd2d634e82/pkg/runtime/cli.go#L51).

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #1026

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [X] Code compiles correctly
* [x] Created/updated tests
* [x] Extended the documentation - https://github.com/dapr/docs/issues/2706

### CODE REVIEW

**Comment by shubham1172** [comment]
The daprd binary already takes care of assigning a free port if it's not present. See [source](https://github.com/dapr/dapr/blob/08a100eda31bffcff929811f14ec79fd2d634e82/pkg/runtime/cli.go#L134-L145)

```go
var daprInternalGRPC int
if *daprInternalGRPCPort != "" {
    daprInternalGRPC, err = strconv.Atoi(*daprInternalGRPCPort)
    if err != nil {
	return nil, errors.Wrap(err, "error parsing dapr-internal-grpc-port")
    }
} else {
    daprInternalGRPC, err = grpc.GetFreePort()
    if err != nil {
	return nil, errors.Wrap(err, "failed to get free port for internal grpc server")
    }
}
```

We can remove this logic from CLI then, following DRY. If the user passes a port number above 0, we can pass it on to Daprd,  else simply skip it.

/cc @mukundansundar

**Comment by pravinpushkar** [comment]
@shubham1172 Should we mention this in documentation?

**Comment by shubham1172** [comment]
> @shubham1172 Should we mention this in documentation?
Thanks, updated the PR description with docs issue.

**Review by pravinpushkar — APPROVED** [review]
lgtm

**Review by mukundansundar — APPROVED** [review]
lgtm

**Pull request merged**
