### PR TITLE
fix(kubernetes/status): pod not ready state will cause panic

### PR DESCRIPTION
**Pull request by 1046102779**
dapr init -k --enable-ha=true  ## use high avaliable method to install dapr

image

image

```shell
# delete pvc
kubectl delete pvc raft-log-dapr-placement-server-0 -n dapr-system
kubectl delete pvc raft-log-dapr-placement-server-1 -n dapr-system
kubectl delete pvc raft-log-dapr-placement-server-2 -n dapr-system

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: raft-log-dapr-placement-server-0
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: cloud.tencent.com/xxx
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: dapr-placement-server
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: cbs
  volumeMode: Filesystem
-----------------------------------------------------------------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: raft-log-dapr-placement-server-1
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: cloud.tencent.com/xxx
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: dapr-placement-server
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: cbs
  volumeMode: Filesystem
---------------------------------------------------------------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: raft-log-dapr-placement-server-2
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: cloud.tencent.com/xxx
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: dapr-placement-server
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: cbs
  volumeMode: Filesystem
```

kubectl apply -f raft-log-dapr-placement-server-0 raft-log-dapr-placement-server-1 raft-log-dapr-placement-server-2 -n dapr-system

image

### CODE REVIEW

**Comment by mukundansundar** [comment]
@1046102779 Can you add a unit test case for this scenario?

**Comment by mukundansundar** [comment]
can you comment on the issue https://github.com/dapr/cli/issues/609 so that it can be assigned to you?

**Comment by 1046102779** [comment]
> @1046102779 Can you add a unit test case for this scenario?

ok

> @1046102779 Can you add a unit test case for this scenario?

yes, please cr

**Review by mukundansundar — APPROVED** [review]
lgtm

**Review by yaron2 — APPROVED** [review]

**Pull request merged**
