### PR TITLE
Support multiple kubeconfigs

### PR DESCRIPTION
**Pull request by qqbuby**
# Description

Support multiple kubeconfigs

```console
$ /usr/local/bin/dapr.org -v
CLI version: 1.7.1
Runtime version: n/a

$ /usr/local/bin/dapr.org status -k
❌  multiple kubeconfigs in KUBECONFIG environment variable - /home/x/.kube/config:/home/x/.kube/local/admin.conf:/home/x/.kube/test/admin.conf


$ /usr/local/bin/dapr-multiple-kubeconfigs status -k
  NAME                   NAMESPACE    HEALTHY  STATUS   REPLICAS  VERSION  AGE  CREATED
  dapr-operator          dapr-system  True     Running  1         1.7.4    5h   2022-06-05 13:49.36
  dapr-sidecar-injector  dapr-system  True     Running  1         1.7.4    5h   2022-06-05 13:49.36
  dapr-sentry            dapr-system  True     Running  1         1.7.4    5h   2022-06-05 13:49.36
  dapr-placement-server  dapr-system  True     Running  1         1.7.4    5h   2022-06-05 13:49.36
  dapr-dashboard         dapr-system  True     Running  1         0.10.0   5h   2022-06-05 13:49.36
```
## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #884

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

### CODE REVIEW

**Comment by yaron2** [comment]
@qqbuby see the failing checks.

**Comment by qqbuby** [comment]
> @qqbuby see the failing checks.

Here is the failing checks error output at **Install Docker - MacOS**: 

```txt
 The application /Applications/Docker.app cannot be opened for an unexpected reason, error=Error Domain=NSOSStatusErrorDomain Code=-600 "procNotFound: no eligible process with specified descriptor" UserInfo={_LSLine=388, _LSFunction=_LSAnnotateAndSendAppleEventWithOptions}
Error: Process completed with exit code 1.
``` 

Maybe we could rerun the test job, or do something else checks on the CI settings?  @yaron2

**Comment by mukundansundar** [comment]
@qqbuby Can you fix the linter errors that you are seeing?

**Comment by qqbuby** [comment]
> @qqbuby Can you fix the linter errors that you are seeing?

It look likes that we need make a approve to run the workflows?

**Comment by qqbuby** [comment]
@yaron2 any updates?

**Review by hueifeng — COMMENTED** [review]
@qqbuby `homeDir`Unused, do we still need to keep it?

**Comment by hueifeng** [comment]
Associated #884

**Comment by qqbuby** [comment]
@hueifeng 

The unused `homeDir` has been deleted.

btw, there is also a recommended function named `HomeDir` at package `k8s.io/client-go/util/homedir` if we need it.

**Comment by hueifeng** [comment]
@qqbuby Please fix DOC.

**Comment by qqbuby** [comment]
> @qqbuby Please fix DCO.

@hueifeng fixed

**Comment by hueifeng** [comment]
@mukundansundar It looks like we need to rerun `checks`.

**Comment by hueifeng** [comment]
@qqbuby hi, can you fix the linter errors?

**Comment by qqbuby** [comment]
> @qqbuby hi, can you fix the linter errors?

@hueifeng i have fixed it, please try to run the checks again.

**Comment by hueifeng** [comment]
@mukundansundar Please rerun checks

**Review by hueifeng — DISMISSED** [review]
LGTM

**Review by mukundansundar — APPROVED** [review]

**Pull request merged**
