### PR TITLE
Handle HTTP status checks in invoke

### PR DESCRIPTION
**Pull request by shubham1172**
Signed-off-by: Shubham Sharma <shubhash@microsoft.com>

# Description

This PR adds HTTP status code handling in `dapr invoke`.

## Issue reference

Please reference the issue this PR will close: #909

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [X] Code compiles correctly
* [x] Created/updated tests
* (NA) Extended the documentation

### CODE REVIEW

**Comment by shubham1172** [comment]
As per the current approach, I am checking for any other status code besides the range [200, 400), and throwing an error with the status message.
image

Do you think it will be helpful to handle each status code separately and have a unique message for them? For example, translate "404 Not Found" to "method name is incorrect"? But that always might be not true, say there is a bug in CLI and it's calling the wrong URL, this will be misleading to the users.

/cc @mukundansundar @pravinpushkar

**Comment by pravinpushkar** [comment]
> As per the current approach, I am checking for any other status code besides the range [200, 400), and throwing an error with the status message. image
> 
> Do you think it will be helpful to handle each status code separately and have a unique message for them? For example, translate "404 Not Found" to "method name is incorrect"? But that always might be not true, say there is a bug in CLI and it's calling the wrong URL, this will be misleading to the users.
> 
> /cc @mukundansundar @pravinpushkar

@shubham1172 It looks fine to me. but If we have a meaningful `response.Body` here, may be we can use that along with current status.

**Comment by shubham1172** [comment]
As discussed, we have created another issue in dapr/dapr for long-term solution for method invocation error (issue 4344). This PR will return error from `Invoke` whenever dapr/dapr does not return a valid status code. Tests will pass once #905 merges.

**Review by mukundansundar — APPROVED** [review]
lgtm

@yaron2 thoughts?

**Comment by yaron2** [comment]
> lgtm
> 
> @yaron2 thoughts?

As the CLI is an aid/tool, this change seems fine to me. I've left a comment regarding https://github.com/dapr/dapr/issues/4344.

**Pull request merged**
