### PR TITLE
Update kubernetes version for CLI e2e tests

### PR DESCRIPTION
**Pull request by wcs1only**
# Description

Updating KinD/k8s version to match dapr/dapr#3367.

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

### CODE REVIEW

**Review by dmitsh — APPROVED** [review]

**Comment by dmitsh** [comment]
@wcs1only , do we also need to apply these changes to .github/workflows/upgrade_e2e.yaml ?

**Comment by wcs1only** [comment]
> @wcs1only , do we also need to apply these changes to .github/workflows/upgrade_e2e.yaml ?

Yes we do, good callout.

**Review by artursouza — APPROVED** [review]

**Comment by artursouza** [comment]
@mukundansundar Please, review since my approval does not count.

**Comment by wcs1only** [comment]
> @mukundansundar Please, review since my approval does not count.

Your approval technically counts, I just think approvers-cli just got write permissions revoked somehow.

**Review by yaron2 — APPROVED** [review]

**Pull request merged**
