### PR TITLE
update dapr to 1.10.0-rc.2

### PR DESCRIPTION
**Pull request by pravinpushkar**
Signed-off-by: Pravin Pushkar <ppushkar@microsoft.com>

# Description

- update dapr to 1.10.0-rc.2
- update kubernetes/configuration_test.go
- update e2e/stanalone/run_test.go

### CODE REVIEW

**Review by shubham1172 — DISMISSED** [review]

**Comment by mukundansundar** [comment]
@pravinpushkar please fix the E2E ... api logging now has a `method` field which is either obfuscated or not...If possible add a test for obfuscation also ...

**Review by mukundansundar — CHANGES_REQUESTED** [review]
left a comment on the changes needed

**Comment by pravinpushkar** [comment]
> @pravinpushkar please fix the E2E ... api logging now has a `method` field which is either obfuscated or not...If possible add a test for obfuscation also ...

yes, thought the changes just got reverted with addition to obfuscation. :(

**Review by mukundansundar — APPROVED** [review]
lgtm

**Review by shubham1172 — APPROVED** [review]

**Comment by mukundansundar** [comment]
@pravinpushkar I do have a question ... between config file and flag in daprd, which takes precedence if one is set to false and the other true for enabling api logging?

**Comment by pravinpushkar** [comment]
> @pravinpushkar I do have a question ... between config file and flag in daprd, which takes precedence if one is set to false and the other true for enabling api logging?

it is the cli flag which takes the precedence

**Comment by mukundansundar** [comment]
> > @pravinpushkar I do have a question ... between config file and flag in daprd, which takes precedence if one is set to false and the other true for enabling api logging?
> 
> it is the cli flag which takes the precedence

Thanks. Just now saw the description as well in this PR https://github.com/dapr/dapr/pull/5866/
>enabled:
                        description: Default value for enabling API logging. Sidecars can always override this by setting `--enable-api-logging` to true or false explicitly. The default value is false.

**Pull request merged**
