### PR TITLE
Make changes for programmatically installing a custom resource

### PR DESCRIPTION
**Pull request by pruthvidhodda**
# Description

Make changes for programmatically installing a custom resource

## Issue reference

Please reference the issue this PR will close: [#_[285]_](https://github.com/dapr/cli/issues/285)

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

### CODE REVIEW

**Comment by yaron2** [comment]
The default configuration is already installed in from https://daprreleases.blob.core.windows.net/manifest/dapr-operator.yaml, isn't it?

**Comment by youngbupark** [comment]
> The default configuration is already installed from https://daprreleases.blob.core.windows.net/manifest/dapr-operator.yaml, isn't it?

this is the cherry-pick of your change in 0.4.0 release. I forgot to cherry pick it from release-0.4.0 to master :)

**Comment by pruthvidhodda** [comment]
> The default configuration is already installed in from https://daprreleases.blob.core.windows.net/manifest/dapr-operator.yaml, isn't it?

The default configuration won't be present in that dapr-operator.yaml anymore because of the changes made in [this PR](https://github.com/dapr/dapr/pull/1218/files).

**Comment by yaron2** [comment]
> > The default configuration is already installed in from https://daprreleases.blob.core.windows.net/manifest/dapr-operator.yaml, isn't it?
> 
> The default configuration won't be present in that dapr-operator.yaml anymore because of the changes made in [this PR](https://github.com/dapr/dapr/pull/1218/files).

Yes, I just caught up on the issue and the conversation there.

My only issue here is that if we remove the configuration CRD from the manifest YAML, it will break users that do `dapr init --kubernetes` with a CLI version < 0.5.0.

@youngbupark what do you think?

**Comment by youngbupark** [comment]
> > > The default configuration is already installed in from https://daprreleases.blob.core.windows.net/manifest/dapr-operator.yaml, isn't it?
> > 
> > 
> > The default configuration won't be present in that dapr-operator.yaml anymore because of the changes made in [this PR](https://github.com/dapr/dapr/pull/1218/files).
> 
> Yes, I just caught up on the issue and the conversation there.
> 
> My only issue here is that if we remove the configuration CRD from the manifest YAML, it will break users that do `dapr init --kubernetes` with a CLI version < 0.5.0.
> 
> @youngbupark what do you think?

The better solution is deploying yaml to github release and then cli refers to github release one. then each dapr version has its own yaml. how do you think ?

**Comment by yaron2** [comment]
> > > > The default configuration is already installed in from https://daprreleases.blob.core.windows.net/manifest/dapr-operator.yaml, isn't it?
> > > 
> > > 
> > > The default configuration won't be present in that dapr-operator.yaml anymore because of the changes made in [this PR](https://github.com/dapr/dapr/pull/1218/files).
> > 
> > 
> > Yes, I just caught up on the issue and the conversation there.
> > My only issue here is that if we remove the configuration CRD from the manifest YAML, it will break users that do `dapr init --kubernetes` with a CLI version < 0.5.0.
> > @youngbupark what do you think?
> 
> The better solution is deploying yaml to github release and then cli refers to github release one. then each dapr version has its own yaml. how do you think ?

If we start from this release, that would indeed be backward compatible.

**Comment by yaron2** [comment]
@youngbupark if we merge this, do you have bandwidth for it?

**Comment by youngbupark** [comment]
> @youngbupark if we merge this, do you have bandwidth for it?

@pruthvidhodda will do :)

**Pull request merged**
