### PR TITLE
Add InvokeGet and Post, refactor Invoke.

### PR DESCRIPTION
**Pull request by vsaroopchand**
# Description

This proposal adds support for HTTP GET to invoke commands. In order to avoid breaking existing scripts using Invoke, I added commands InvokeGet and InvokePost and updated the description to make Invoke obsolete. I also refactored pkg/invoke to accommodate the new commands.

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #224 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

### CODE REVIEW

**Comment by yaron2** [comment]
Thanks!

I trust you've tested `invokeGet` and `invokePost` with an app listening on GET and POST endpoints?

**Comment by vsaroopchand** [comment]
Tested with the hello-world sample app on standalone. Here is the output.

cli invokePost --app-id nodeapp --method neworder --payload "{\"data\": { \"orderId\": \"46\" } }"
HTTP Post to method neworder invoked successfully

cli invokeGet --app-id nodeapp --method order
{"orderId":"46"}
HTTP Get to method order invoked successfully

**Comment by yaron2** [comment]
lgtm.

/cc @msfusell

The invoke command remains but is deprecated in favor of invokeGet and invokePost.

**Comment by yaron2** [comment]
I assume this was closed by mistake?

**Comment by vsaroopchand** [comment]
My bad - closed by mistake :)

**Comment by yaron2** [comment]
Thanks!

**Pull request merged**
