### PR TITLE
Parallel exec for UTs and cache go dep

### PR DESCRIPTION
**Pull request by pravinpushkar**
Signed-off-by: Pravin Pushkar <ppushkar@microsoft.com>

### CODE REVIEW

**Review by mukundansundar — CHANGES_REQUESTED** [review]
change go version to latest in 1.19 .... @pravinpushkar

**Comment by pravinpushkar** [comment]
> change go version to latest in 1.19 .... @pravinpushkar

Should we try to update to 1.20 ?

**Comment by mukundansundar** [comment]
> > change go version to latest in 1.19 .... @pravinpushkar
> 
> 
> 
> Should we try to update to 1.20 ?

Do we have the runners? Should be a separate issue and pr...

**Review by mukundansundar — APPROVED** [review]
lgtm

**Pull request merged**
