### PR TITLE
upgrade go version

### PR DESCRIPTION
**Pull request by pravinpushkar**
Signed-off-by: Pravin Pushkar <ppushkar@microsoft.com>

# Description

Go version updated

## Issue reference

Please reference the issue this PR will close: #1060

### CODE REVIEW

**Review by shubham1172 — APPROVED** [review]

**Comment by shubham1172** [comment]
Leaving release docs here https://tip.golang.org/doc/go1.19, LGTM

**Comment by mukundansundar** [comment]
@pravinpushkar Did you observe any changes wrt the os-exec-path ??

**Review by mukundansundar — APPROVED** [review]
LGTM. only question is how does os-exec-path change affect the CLI behavior. 
@yaron2 Any concerns with this change?

**Comment by pravinpushkar** [comment]
@mukundansundar @shubham1172 The breaking change introduced is regarding the path lookups in `exec.Command` and `exec. LookPath`.  They no longer searches for paths w.r.t the current directory. I did a cursory look at our usecases in this repo and it seems we we are good here.

**Pull request merged**
