### PR TITLE
Add `--output` option to `dapr list`

### PR DESCRIPTION
**Pull request by philliphoff**
# Description

Adds an `--output` to `dapr list` that allows the user to specify an alternative output format.  Valid values are `json`, `yaml`, and `table` (the default if omitted). Invalid values result in an error message.

This allows tools and other automation to more easily consume the list of running Dapr applications.

Examples:

```bash
% ./dist/darwin_amd64/release/dapr list -k         
  APP ID   APP PORT  AGE  CREATED              
  nodeapp  3000      18h  2021-05-25 16:22.30  

% ./dist/darwin_amd64/release/dapr list -k -o table
  APP ID   APP PORT  AGE  CREATED              
  nodeapp  3000      18h  2021-05-25 16:22.30  

% ./dist/darwin_amd64/release/dapr list -k -o json 
{
  "appId": "nodeapp",
  "appPort": "3000",
  "age": "18h",
  "created": "2021-05-25 16:22.30"
}%  
                                                                                                                                                                                                    
% ./dist/darwin_amd64/release/dapr list -k -o yaml
appId: nodeapp
appPort: "3000"
age: 18h
created: 2021-05-25 16:22.30

% ./dist/darwin_amd64/release/dapr list            
  APP ID   HTTP PORT  GRPC PORT  APP PORT  COMMAND  AGE  CREATED              PID    
  app-one  55206      55207      0                  41m  2021-05-26 09:55.39  93908  

% ./dist/darwin_amd64/release/dapr list -o table
  APP ID   HTTP PORT  GRPC PORT  APP PORT  COMMAND  AGE  CREATED              PID    
  app-one  55206      55207      0                  41m  2021-05-26 09:55.39  93908  

% ./dist/darwin_amd64/release/dapr list -o json 
{
  "appId": "app-one",
  "httpPort": 55206,
  "grpcPort": 55207,
  "appPort": 0,
  "metricsEnabled": true,
  "command": "",
  "age": "41m",
  "created": "2021-05-26 09:55.39",
  "pid": 93908
}%                
                                                                                                                                                                                      
% ./dist/darwin_amd64/release/dapr list -o yaml
appId: app-one
httpPort: 55206
grpcPort: 55207
appPort: 0
metricsEnabled: true
command: ""
age: 41m
created: 2021-05-26 09:55.39
pid: 93908

 % ./dist/darwin_amd64/release/dapr list -o invalid  
❌  An invalid output format was specified.
```

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #728

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Extended the documentation (drafted PR [dapr/docs#1512](https://github.com/dapr/docs/pull/1512))

### CODE REVIEW

**Comment by mukundansundar** [comment]
@philliphoff Can you add e2e tests for this ?

**Comment by philliphoff** [comment]
@ mukundansundar Expanded on the `list` E2E tests.

**Review by mukundansundar — COMMENTED** [review]
@philliphoff lgtm ... Could you add the same check for Kubernetes also ?

**Comment by philliphoff** [comment]
@mukundansundar There aren't any existing `list` related tests on the Kubernetes side, nor does it appear that any of the E2E tests actually install an application that one could "list".

What's the simplest way to get a Dapr sidecar running within a cluster?  Is it possible without having to scaffold and deploy an entire application?

**Comment by mukundansundar** [comment]
> @mukundansundar There aren't any existing `list` related tests on the Kubernetes side, nor does it appear that any of the E2E tests actually install an application that one could "list".
> 
> What's the simplest way to get a Dapr sidecar running within a cluster? Is it possible without having to scaffold and deploy an entire application?

I agree that k8s test for list from scratch is outside of this PR. Right now the way is to scaffold and deploy an entire application.

**Review by mukundansundar — COMMENTED** [review]
lgtm. 
Could you take a look at the linter failure?
Can you add the e2e test for the invalid scenario also?

**Comment by philliphoff** [comment]
@mukundansundar Resolved linter issues and added test case.

**Review by mukundansundar — APPROVED** [review]

**Comment by philliphoff** [comment]
@mukundansundar Any movement on this?

**Review by wcs1only — APPROVED** [review]

**Comment by yaron2** [comment]
@philliphoff the only thing missing is an example to the README for the new flag. I'll merge this once it is added.

**Review by yaron2 — APPROVED** [review]
lgtm

**Pull request merged**
