### PR TITLE
Added new holopin cli badge

### PR DESCRIPTION
**Pull request by rishabkumar7**
# Description

Added the new Holopin cli badge.

## Issue reference

Please reference the issue this PR will close: #1398 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

### CODE REVIEW

**Review by mukundansundar — APPROVED** [review]

**Review by mikeee — APPROVED** [review]

**Comment by marcduiker** [comment]
@dapr/maintainers-cli can you restart the E2E tests please? Or somehow resolve this issue and merge? This change is only about a yaml for for the Holopin bot to award badges for this repo.

**Comment by marcduiker** [comment]
@dapr/maintainers-cli any chance of re-running the e2e test again to get this PR merged? Or ignore the e2e. The only addition is a github config file.

**Review by yaron2 — APPROVED** [review]

**Comment by marcduiker** [comment]
@holopin-bot @rishabkumar7 

You made it Rishab! Thanks for your patience! 😁

**Pull request merged**
