### PR TITLE
Delete remove image logic from uninstall

### PR DESCRIPTION
**Pull request by pravinpushkar**
Signed-off-by: Pravin Pushkar <ppushkar@microsoft.com>

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #1093

### CODE REVIEW

**Comment by mukundansundar** [comment]
@pravinpushkar why are there changes in go.sum file

**Comment by pravinpushkar** [comment]
> @pravinpushkar why are there changes in go.sum file

Looks like previous PR did not run modtidy. I can see multiple entries - 

github.com/dapr/components-contrib v1.9.0-rc.1 h1:8qC2QPvvJ9odzAv6cRrZBttTuxYnPK7dAZ+HMNI/okA=
github.com/dapr/components-contrib v1.9.0-rc.1/go.mod h1:ftVthBjl0e5G61J5XKkZKEjU/TGE0gNT9fJCNAdUjU8=
github.com/dapr/components-contrib v1.9.0-rc.2 h1:on1JPIJZojjMu929b/rFbIaVZja6K2Z/hc+BVZ4OTNY=
github.com/dapr/components-contrib v1.9.0-rc.2/go.mod h1:ftVthBjl0e5G61J5XKkZKEjU/TGE0gNT9fJCNAdUjU8=
github.com/dapr/dapr v1.9.0-rc.3 h1:WLATw9Ky44lM5CVbzrd/M04yQXON4+NL9GH6K89v8Mo=
github.com/dapr/dapr v1.9.0-rc.3/go.mod h1:LUNByfXcsSuvXkNFZq+JCsgiCgAZO3uaQDu5LCheBj8=
github.com/dapr/dapr v1.9.0-rc.5 h1:bWkt5urk0x6G+PtegVO+p7ZK1bneuvHdA/z+STWeyqw=
github.com/dapr/dapr v1.9.0-rc.5/go.mod h1:DBQVjCSQ2/Lh4rBi1b4oSQXl+yH2WTb6orrZ7Jkro88=

**Review by mukundansundar — APPROVED** [review]

**Comment by shubham1172** [comment]
Since it is a change in behavior, do you think it's worth calling it out somewhere in docs?

**Comment by mukundansundar** [comment]
> Since it is a change in behavior, do you think it's worth calling it out somewhere in docs?

Try out the command it runs

`docker rmi -f daprio/dapr`

That command never works.... It has not worked at all without the tag being correctly present. So Imo this is not a change in behavior.

**Review by mukundansundar — APPROVED** [review]

**Pull request merged**
